/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as BundleRouteImport } from './routes/bundle'
import { Route as BuilderRouteRouteImport } from './routes/builder/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminologyIndexRouteImport } from './routes/terminology/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as TerminologySystemIdRouteImport } from './routes/terminology/$systemId'
import { Route as BuilderResourceTypeIndexRouteImport } from './routes/builder/$resourceType/index'
import { Route as BuilderResourceTypeEntryIndexRouteImport } from './routes/builder/$resourceType/$entryIndex'

const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleRoute = BundleRouteImport.update({
  id: '/bundle',
  path: '/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRouteRoute = BuilderRouteRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminologyIndexRoute = TerminologyIndexRouteImport.update({
  id: '/terminology/',
  path: '/terminology/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const TerminologySystemIdRoute = TerminologySystemIdRouteImport.update({
  id: '/terminology/$systemId',
  path: '/terminology/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderResourceTypeIndexRoute =
  BuilderResourceTypeIndexRouteImport.update({
    id: '/$resourceType/',
    path: '/$resourceType/',
    getParentRoute: () => BuilderRouteRoute,
  } as any)
const BuilderResourceTypeEntryIndexRoute =
  BuilderResourceTypeEntryIndexRouteImport.update({
    id: '/$resourceType/$entryIndex',
    path: '/$resourceType/$entryIndex',
    getParentRoute: () => BuilderRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteRouteWithChildren
  '/bundle': typeof BundleRoute
  '/exchange': typeof ExchangeRoute
  '/terminology/$systemId': typeof TerminologySystemIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/terminology/': typeof TerminologyIndexRoute
  '/builder/$resourceType/$entryIndex': typeof BuilderResourceTypeEntryIndexRoute
  '/builder/$resourceType/': typeof BuilderResourceTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundle': typeof BundleRoute
  '/exchange': typeof ExchangeRoute
  '/terminology/$systemId': typeof TerminologySystemIdRoute
  '/builder': typeof BuilderIndexRoute
  '/terminology': typeof TerminologyIndexRoute
  '/builder/$resourceType/$entryIndex': typeof BuilderResourceTypeEntryIndexRoute
  '/builder/$resourceType': typeof BuilderResourceTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRouteRouteWithChildren
  '/bundle': typeof BundleRoute
  '/exchange': typeof ExchangeRoute
  '/terminology/$systemId': typeof TerminologySystemIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/terminology/': typeof TerminologyIndexRoute
  '/builder/$resourceType/$entryIndex': typeof BuilderResourceTypeEntryIndexRoute
  '/builder/$resourceType/': typeof BuilderResourceTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/bundle'
    | '/exchange'
    | '/terminology/$systemId'
    | '/builder/'
    | '/terminology/'
    | '/builder/$resourceType/$entryIndex'
    | '/builder/$resourceType/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundle'
    | '/exchange'
    | '/terminology/$systemId'
    | '/builder'
    | '/terminology'
    | '/builder/$resourceType/$entryIndex'
    | '/builder/$resourceType'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/bundle'
    | '/exchange'
    | '/terminology/$systemId'
    | '/builder/'
    | '/terminology/'
    | '/builder/$resourceType/$entryIndex'
    | '/builder/$resourceType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRouteRoute: typeof BuilderRouteRouteWithChildren
  BundleRoute: typeof BundleRoute
  ExchangeRoute: typeof ExchangeRoute
  TerminologySystemIdRoute: typeof TerminologySystemIdRoute
  TerminologyIndexRoute: typeof TerminologyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle': {
      id: '/bundle'
      path: '/bundle'
      fullPath: '/bundle'
      preLoaderRoute: typeof BundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminology/': {
      id: '/terminology/'
      path: '/terminology'
      fullPath: '/terminology/'
      preLoaderRoute: typeof TerminologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/terminology/$systemId': {
      id: '/terminology/$systemId'
      path: '/terminology/$systemId'
      fullPath: '/terminology/$systemId'
      preLoaderRoute: typeof TerminologySystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/$resourceType/': {
      id: '/builder/$resourceType/'
      path: '/$resourceType'
      fullPath: '/builder/$resourceType/'
      preLoaderRoute: typeof BuilderResourceTypeIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder/$resourceType/$entryIndex': {
      id: '/builder/$resourceType/$entryIndex'
      path: '/$resourceType/$entryIndex'
      fullPath: '/builder/$resourceType/$entryIndex'
      preLoaderRoute: typeof BuilderResourceTypeEntryIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
  }
}

interface BuilderRouteRouteChildren {
  BuilderIndexRoute: typeof BuilderIndexRoute
  BuilderResourceTypeEntryIndexRoute: typeof BuilderResourceTypeEntryIndexRoute
  BuilderResourceTypeIndexRoute: typeof BuilderResourceTypeIndexRoute
}

const BuilderRouteRouteChildren: BuilderRouteRouteChildren = {
  BuilderIndexRoute: BuilderIndexRoute,
  BuilderResourceTypeEntryIndexRoute: BuilderResourceTypeEntryIndexRoute,
  BuilderResourceTypeIndexRoute: BuilderResourceTypeIndexRoute,
}

const BuilderRouteRouteWithChildren = BuilderRouteRoute._addFileChildren(
  BuilderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRouteRoute: BuilderRouteRouteWithChildren,
  BundleRoute: BundleRoute,
  ExchangeRoute: ExchangeRoute,
  TerminologySystemIdRoute: TerminologySystemIdRoute,
  TerminologyIndexRoute: TerminologyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
